; ROCm 10.1 / HIP 7.16 / clang 24; generated by the fresh hipcc oracle procedure.
v_mul_f32_e32 v0, 0xbfb8aa3b, v84
v_cmp_nlt_f32_e64 s0, 0x42ce8ed0, v84
v_rndne_f32_e32 v3, v0
v_fma_f32 v2, 0xbfb8aa3b, v84, -v0
v_dual_sub_f32 v4, v0, v3
v_cvt_i32_f32_e32 v3, v3
v_fmac_f32_e32 v2, 0xb2a5705f, v84
v_dual_add_f32 v2, v4, v2
v_exp_f32_e32 v2, v2
v_ldexp_f32 v2, v2, v3
v_cndmask_b32_e64 v2, 0, v2, s0
v_cmp_ngt_f32_e64 s1, 0xc2b17218, v84
v_cndmask_b32_e64 v2, 0x7f800000, v2, s1
v_dual_add_f32 v2, 1.0, v2
v_div_scale_f32 v11, null, v2, v2, v84
v_rcp_f32_e32 v13, v11
v_fma_f32 v14, -v11, v13, 1.0
v_fmac_f32_e32 v13, v14, v13
v_div_scale_f32 v3, vcc_lo, v84, v2, v84
v_mul_f32_e32 v14, v3, v13
v_fma_f32 v18, -v11, v14, v3
v_fmac_f32_e32 v14, v18, v13
v_fma_f32 v3, -v11, v14, v3
v_div_fmas_f32 v3, v3, v13, v14
v_div_fixup_f32 v1, v3, v2, v84
v_dual_mul_f32 v1, v1, v83
