; ROCm 10.1 / HIP 7.16 / clang 24; generated by the fresh hipcc oracle procedure.
v_dual_mul_f32 v8, 0xbfb8aa3b, v162
v_cmp_nlt_f32_e64 s14, 0x42ce8ed0, v162
v_cmp_ngt_f32_e64 s15, 0xc2b17218, v162
v_rndne_f32_e32 v14, v8
v_fma_f32 v16, 0xbfb8aa3b, v162, -v8
v_sub_f32_e32 v15, v8, v14
v_fmac_f32_e32 v16, 0xb2a5705f, v162
v_cvt_i32_f32_e32 v14, v14
v_add_f32_e32 v15, v15, v16
v_exp_f32_e32 v15, v15
v_ldexp_f32 v14, v15, v14
v_cndmask_b32_e64 v14, 0, v14, s14
v_cndmask_b32_e64 v14, 0x7f800000, v14, s15
v_add_f32_e32 v14, 1.0, v14
v_div_scale_f32 v15, null, v14, v14, v162
v_rcp_f32_e32 v16, v15
v_fma_f32 v17, -v15, v16, 1.0
v_fmac_f32_e32 v16, v17, v16
v_div_scale_f32 v17, vcc_lo, v162, v14, v162
v_mul_f32_e32 v18, v17, v16
v_fma_f32 v19, -v15, v18, v17
v_fmac_f32_e32 v18, v19, v16
v_fma_f32 v15, -v15, v18, v17
s_wait_alu depctr_va_vcc(0)
v_div_fmas_f32 v15, v15, v16, v18
v_div_fixup_f32 v14, v15, v14, v162
v_mul_f32_e32 v14, v164, v14
