// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Kaden Schutt
// hipfire — see LICENSE and NOTICE in the project root.
//! GPU side of the NPU persistent ring (`docs/npu/railgun-npu.md` §3.1, §4): PM-native gfx1151 kernels
//! (`native/coop_ring_gfx1151.s`, regenerated by `native/build-coop-ring.sh`) and their kernel-argument blobs.
//! The ring, A arena and C arena are HIP VMM host allocations of kind `VmmHostUncached`, exported as dma-buf and
//! imported by the NPU; the kernels bypass GL0/GL1 on loads (`glc dlc`) and store `glc slc dlc`, so no cache
//! maintenance packet is needed on uncached memory. The CPU touches that memory only through HIP copies
//! (`upload` / `download` / `memset`): a CPU mmap of the dma-buf (directly or through the amdxdna import) does not see
//! the GPU's bytes nor do its stores reach the GPU (measured, `docs/coop-flashnext.md`).
//!
//! * `coop_copy` (block [`COPY_BLOCK`]): grid-stride 16-byte copy; producer (A into the slot arena) and consumer (C out
//!   of the slot arena into device memory).
//! * `coop_publish` (block [`LANE_BLOCK`], one lane): optional slot-free wait (`done == free_ref`), then publish
//!   `seq` to the slot line and poll the done line for `seq`, recording GPU realtime stamps ([`PublishRecord`]).

pub const CODE_OBJECT: &[u8] = include_bytes!("../native/coop_ring_gfx1151.co");
pub const ARCH: &str = "gfx1151";
pub const COPY: &str = "coop_copy";
pub const PUBLISH: &str = "coop_publish";
pub const COPY_BLOCK: u32 = 256;
pub const LANE_BLOCK: u32 = 32;
pub const PUBLISH_RECORD_BYTES: usize = 64;
pub const STATUS_OK: u32 = 1;
pub const STATUS_DONE_TIMEOUT: u32 = 2;
pub const STATUS_NOT_FREED: u32 = 3;

pub fn copy_args(dst: u64, src: u64, count16: u64, stride: u64) -> [u8; 32] {
    let mut a = [0u8; 32];
    for (i, v) in [dst, src, count16, stride].into_iter().enumerate() {
        a[8 * i..8 * i + 8].copy_from_slice(&v.to_le_bytes());
    }
    a
}

/// `wait_free`: poll the done line for `free_ref` first (a slot is reused only after its previous seq is done).
pub fn publish_args(seq_addr: u64, done_addr: u64, stats: u64, seq: u32, free_ref: u32, max_iters: u32, wait_free: bool) -> [u8; 40] {
    let mut a = [0u8; 40];
    a[0..8].copy_from_slice(&seq_addr.to_le_bytes());
    a[8..16].copy_from_slice(&done_addr.to_le_bytes());
    a[16..24].copy_from_slice(&stats.to_le_bytes());
    for (i, v) in [seq, free_ref, max_iters, wait_free as u32].into_iter().enumerate() {
        a[24 + 4 * i..28 + 4 * i].copy_from_slice(&v.to_le_bytes());
    }
    a
}

fn u32_at(b: &[u8], at: usize) -> u32 {
    u32::from_le_bytes(b[at..at + 4].try_into().unwrap())
}
fn u64_at(b: &[u8], at: usize) -> u64 {
    u64::from_le_bytes(b[at..at + 8].try_into().unwrap())
}

/// One `coop_publish` record (GPU realtime ticks).
#[derive(Clone, Copy, Debug, Default)]
pub struct PublishRecord {
    /// Before the seq store (after the slot-free wait).
    pub t_start: u64,
    /// After the seq store completed (`s_waitcnt_vscnt 0`).
    pub t_pub: u64,
    /// When the load that saw `seq` on the done line returned.
    pub t_obs: u64,
    pub poll_iters: u32,
    pub status: u32,
    pub free_iters: u32,
    pub last_done: u32,
    pub seq: u32,
    /// Issue time of the load that saw `seq`.
    pub t_hit_issue: u64,
    /// Issue time of the last load that did not see it (`t_pub` when the first load hit): the done line became
    /// visible to the GPU in `(t_miss_issue, t_obs]`.
    pub t_miss_issue: u64,
}

impl PublishRecord {
    pub fn parse(b: &[u8]) -> Self {
        PublishRecord {
            t_start: u64_at(b, 0),
            t_pub: u64_at(b, 8),
            t_obs: u64_at(b, 16),
            poll_iters: u32_at(b, 24),
            status: u32_at(b, 28),
            free_iters: u32_at(b, 32),
            last_done: u32_at(b, 36),
            seq: u32_at(b, 40),
            t_hit_issue: u64_at(b, 48),
            t_miss_issue: u64_at(b, 56),
        }
    }
}
