// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Kaden Schutt
// hipfire — see LICENSE and NOTICE in the project root.
//! Generate checked-in Rust AIE2P metadata; no vendor compiler or runtime.
//!
//! Usage: `tblgen --llvm ref/llvm-aie --output crates/pm-npu/src/isa/gen.rs`
//! Requires upstream llvm-tblgen-18 and its include directory. The temporary
//! compatibility root excludes compiler ISel patterns, not encoding records; it
//! preserves dontcare as variables instead of TableGen's default zero. Generated
//! runtime code has no dependency on Python, LLVM, or the reference checkout.

use regex::Regex;
use serde_json::Value;
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

const HEADER: &str = r#"// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
// Derived from Xilinx/llvm-aie AIE2P TableGen and MC operand encoders.
// Generated by npu-tools tblgen2rs; do not edit the tables by hand.
//! Complete resolved slot, composite format, operand and instruction metadata.

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum Slot { Ldb, Alu, Lng, Lda, Mv, St, Vec, Nop16 }
impl Slot {
    pub const fn width(self) -> u8 { [17,20,42,20,22,20,26,1][self as usize] }
}
#[derive(Clone, Copy, Debug)]
pub struct BitField { pub name: &'static str, pub lsb: u8, pub width: u8, pub source_lsb: u8 }
#[derive(Clone, Copy, Debug)]
pub struct SlotField { pub slot: Slot, pub lsb: u8, pub width: u8 }
#[derive(Clone, Copy, Debug)]
pub struct Format { pub name: &'static str, pub bits: u8, pub mask: u128, pub value: u128, pub slots: &'static [SlotField], pub dontcare_mask: u128 }
#[derive(Clone, Copy, Debug)]
pub struct RegisterEncoding { pub name: &'static str, pub asm: &'static str, pub value: u64 }
#[derive(Clone, Copy, Debug)]
pub struct Operand { pub name: &'static str, pub kind: &'static str, pub width: u8, pub output: bool, pub encoder: &'static str, pub decoder: &'static str, pub printer: &'static str, pub registers: &'static [RegisterEncoding] }
#[derive(Clone, Copy, Debug)]
pub struct Encoding { pub name: &'static str, pub mnemonic: &'static str, pub asm: &'static str, pub slot: Slot, pub mask: u64, pub value: u64, pub dontcare_mask: u64, pub fields: &'static [BitField], pub operands: &'static [Operand], pub itinerary: &'static str, pub constraints: &'static str }
"#;

const DESCRIPTION: &str = "Generate checked-in Rust AIE2P metadata; no vendor compiler or runtime.\n\nUsage: npu-tools tblgen2rs --llvm ref/llvm-aie --output crates/pm-npu/src/isa/gen.rs\nRequires upstream llvm-tblgen-18 and its include directory. The temporary\ncompatibility root excludes compiler ISel patterns, not encoding records; it\npreserves dontcare as variables instead of TableGen's default zero. Generated\nruntime code has no dependency on Python, LLVM, or the reference checkout.\n";

type Res<T> = Result<T, String>;

/// Equivalent of `json.dumps(value, ensure_ascii=True)` for a string.
fn q(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\u{8}' => out.push_str("\\b"),
            '\u{c}' => out.push_str("\\f"),
            ' '..='~' => out.push(c),
            _ => {
                let mut buf = [0u16; 2];
                for unit in c.encode_utf16(&mut buf) {
                    out.push_str(&format!("\\u{:04x}", unit));
                }
            }
        }
    }
    out.push('"');
    out
}

fn get<'a>(v: &'a Value, key: &str) -> Res<&'a Value> {
    v.get(key).ok_or_else(|| format!("KeyError: {key:?}"))
}

fn str_of(v: &Value) -> Res<&str> {
    v.as_str().ok_or_else(|| format!("expected string, got {v}"))
}

fn array_of(v: &Value) -> Res<&Vec<Value>> {
    v.as_array().ok_or_else(|| format!("expected array, got {v}"))
}

fn uint_of(v: &Value) -> Res<u64> {
    v.as_u64().ok_or_else(|| format!("expected unsigned integer, got {v}"))
}

fn truthy(v: &Value) -> bool {
    match v {
        Value::Null => false,
        Value::Bool(b) => *b,
        Value::Number(n) => n.as_f64().map_or(true, |f| f != 0.0),
        Value::String(s) => !s.is_empty(),
        Value::Array(a) => !a.is_empty(),
        Value::Object(o) => !o.is_empty(),
    }
}

/// Optional string field with a default; an explicit non-string value is an error.
fn opt_str<'a>(v: &'a Value, key: &str, default: &'a str) -> Res<&'a str> {
    match v.get(key) {
        None => Ok(default),
        Some(x) => str_of(x),
    }
}

fn has_super(record: &Value, name: &str) -> Res<bool> {
    Ok(array_of(get(record, "!superclasses")?)?
        .iter()
        .any(|s| s.as_str() == Some(name)))
}

fn integer(bits: &[Value]) -> Res<u128> {
    let mut out = 0u128;
    for (i, bit) in bits.iter().enumerate() {
        let b = match bit.as_u64() {
            Some(b @ (0 | 1)) => b as u128,
            _ => return Err(format!("assertion failed: bit {bit} not in (0, 1)")),
        };
        if i >= 128 {
            return Err("integer wider than 128 bits".into());
        }
        out |= b << i;
    }
    Ok(out)
}

struct Field {
    name: String,
    lsb: usize,
    width: usize,
    source: u64,
}

fn bit_layout(bits: &[Value]) -> Res<(u128, u128, u128, Vec<Field>)> {
    let (mut mask, mut value, mut dc) = (0u128, 0u128, 0u128);
    let mut fields: Vec<Field> = Vec::new();
    for (i, bit) in bits.iter().enumerate() {
        if i >= 128 {
            return Err("bit layout wider than 128 bits".into());
        }
        if bit.is_i64() || bit.is_u64() {
            let b = match bit.as_u64() {
                Some(b @ (0 | 1)) => b as u128,
                _ => return Err(format!("unsupported constant bit {bit}")),
            };
            mask |= 1 << i;
            value |= b << i;
        } else if bit.is_null() || bit.get("var").and_then(Value::as_str) == Some("dontcare") {
            dc |= 1 << i;
        } else {
            if get(bit, "kind").ok().and_then(Value::as_str) != Some("varbit") {
                return Err(format!("assertion failed: {bit}"));
            }
            let var = str_of(get(bit, "var")?)?;
            let index = uint_of(get(bit, "index")?)?;
            if let Some(last) = fields.last_mut() {
                if last.name == var && last.lsb + last.width == i && last.source + last.width as u64 == index {
                    last.width += 1;
                    continue;
                }
            }
            fields.push(Field { name: var.to_string(), lsb: i, width: 1, source: index });
        }
    }
    Ok((mask, value, dc, fields))
}

/// Python `Path.read_text()`: UTF-8 with universal newlines.
fn read_text(path: &Path) -> Res<String> {
    let text = fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
    if text.contains('\r') {
        Ok(text.replace("\r\n", "\n").replace('\r', "\n"))
    } else {
        Ok(text)
    }
}

fn write_text(path: &Path, text: &str) -> Res<()> {
    fs::write(path, text).map_err(|e| format!("{}: {e}", path.display()))
}

/// Removes the staging directory on every exit path, including failures and panics.
struct TempDir(PathBuf);

impl TempDir {
    fn new(prefix: &str) -> Res<TempDir> {
        use std::os::unix::fs::DirBuilderExt;
        let base = std::env::temp_dir();
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map_or(0, |d| d.as_nanos());
        for attempt in 0..64u128 {
            let path = base.join(format!("{prefix}{:x}{:x}", std::process::id(), nanos.wrapping_add(attempt)));
            match fs::DirBuilder::new().mode(0o700).create(&path) {
                Ok(()) => return Ok(TempDir(path)),
                Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => continue,
                Err(e) => return Err(format!("{}: {e}", path.display())),
            }
        }
        Err("no usable temporary directory name".into())
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn dump_records(llvm: &Path, tblgen: &str, upstream: &Path) -> Res<Value> {
    let target = llvm.join("llvm/lib/Target/AIE");
    let include = llvm.join("llvm/include");
    let tmp = TempDir::new("tblgen2rs-")?;
    let stage = tmp.0.as_path();
    let mkdir = |p: PathBuf| fs::create_dir_all(&p).map_err(|e| format!("{}: {e}", p.display()));
    mkdir(stage.join("llvm/Target"))?;
    mkdir(stage.join("aie2p"))?;
    // LLVM 18 can resolve ISA records but not current compiler IR patterns.
    let text = read_text(&include.join("llvm/Target/Target.td"))?;
    write_text(
        &stage.join("llvm/Target/Target.td"),
        &text.replace("include \"llvm/Target/TargetMacroFusion.td\"", ""),
    )?;
    let text = read_text(&target.join("aie2p/AIE2PInstrInfo.td"))?;
    write_text(
        &stage.join("aie2p/AIE2PInstrInfo.td"),
        &text.replace("include \"aie2p/AIE2PInstrPatterns.td\"", ""),
    )?;
    let text = read_text(&target.join("AIEBaseInstrFormats.td"))?;
    write_text(
        &stage.join("AIEBaseInstrFormats.td"),
        &text.replace("field bits<32> dontcare = 0;", "field bits<32> dontcare;"),
    )?;
    let old = read_text(&upstream.join("llvm/CodeGen/ValueTypes.td"))?;
    let def_re = Regex::new(r"def\s+(\w+)\s*:").unwrap();
    let names: HashSet<&str> = def_re.captures_iter(&old).map(|c| c.get(1).unwrap().as_str()).collect();
    let mut extra: Vec<String> = Vec::new();
    let new = read_text(&include.join("llvm/CodeGen/ValueTypes.td"))?;
    let vt_re = Regex::new(r"def\s+(\w+)\s*:\s*(\w+)<([^;]+)>\s*;").unwrap();
    for c in vt_re.captures_iter(&new) {
        let (name, cls, args) = (&c[1], &c[2], &c[3]);
        if names.contains(name) {
            continue;
        }
        let parts: Vec<&str> = args.split(',').collect();
        if cls == "VTInt" || cls == "ValueType" {
            extra.push(format!("def {name} : ValueType<{args}>;"));
        } else if cls == "VTVec" {
            let second = parts.get(1).ok_or("IndexError: list index out of range")?;
            if second.trim() == "i48" {
                let n: i128 = parts[0]
                    .trim()
                    .parse()
                    .map_err(|_| format!("ValueError: invalid literal for int(): {:?}", parts[0]))?;
                extra.push(format!("def {name} : ValueType<{}, {}>;", n * 48, parts[parts.len() - 1]));
            }
        }
    }
    let root = stage.join("isa.td");
    write_text(
        &root,
        &format!(
            "include \"llvm/Target/Target.td\"\n{}\ninclude \"llvm/Target/AIETarget.td\"\ninclude \"llvm/Target/CodeGenFormat.td\"\ninclude \"aie2p/AIE2PRegisterInfo.td\"\ninclude \"aie2p/AIE2PSchedule.td\"\ninclude \"aie2p/AIE2PInstrInfo.td\"\n",
            extra.join("\n")
        ),
    )?;
    let output = stage.join("records.json");
    let mut command = Command::new(tblgen);
    command.arg("--dump-json");
    for path in [stage, upstream, include.as_path(), target.as_path(), target.join("aie2p").as_path()] {
        command.arg("-I").arg(path);
    }
    command.arg(&root).arg("-o").arg(&output);
    let status = command.status().map_err(|e| format!("{tblgen}: {e}"))?;
    if !status.success() {
        return Err(format!("Command '{tblgen}' returned non-zero exit status {status}"));
    }
    let raw = fs::read_to_string(&output).map_err(|e| format!("{}: {e}", output.display()))?;
    serde_json::from_str(&raw).map_err(|e| format!("records.json: {e}"))
}

fn slot_name(key: &str) -> Res<&'static str> {
    Ok(match key {
        "ldb" => "Ldb",
        "alu" => "Alu",
        "lng" => "Lng",
        "lda" => "Lda",
        "mv" => "Mv",
        "st" => "St",
        "vec" => "Vec",
        "nop" | "nop16" => "Nop16",
        _ => return Err(format!("KeyError: {key:?}")),
    })
}

struct Rule {
    regs: Vec<String>,
    shift: Option<u32>,
    value: u128,
}

struct Gen<'a> {
    records: &'a Value,
    members_cache: HashMap<String, Vec<String>>,
}

fn parse_bin(text: &str) -> Res<u128> {
    u128::from_str_radix(text.trim_start_matches("0b"), 2).map_err(|e| format!("{text}: {e}"))
}

impl<'a> Gen<'a> {
    fn record(&self, name: &str) -> Res<&'a Value> {
        self.records.get(name).ok_or_else(|| format!("KeyError: {name:?}"))
    }

    fn members(&mut self, name: &str) -> Res<Vec<String>> {
        if let Some(hit) = self.members_cache.get(name) {
            return Ok(hit.clone());
        }
        let record = self.record(name)?;
        let result: Vec<String> = if has_super(record, "Register")? {
            vec![name.to_string()]
        } else {
            let dag = get(record, "MemberList")?;
            if get(get(dag, "operator")?, "def")?.as_str() != Some("add") {
                return Err(format!("assertion failed: {dag}"));
            }
            let mut result: Vec<String> = Vec::new();
            for item in array_of(get(dag, "args")?)? {
                let arg = item.get(0).ok_or("dag arg missing")?;
                if get(arg, "kind")?.as_str() != Some("def") {
                    return Err(format!("assertion failed: {arg}"));
                }
                result.extend(self.members(str_of(get(arg, "def")?)?)?);
            }
            let mut seen = HashSet::new();
            result.retain(|r| seen.insert(r.clone()));
            result
        };
        self.members_cache.insert(name.to_string(), result.clone());
        Ok(result)
    }

    fn reg_table(&mut self, methods: &HashMap<String, Vec<Rule>>, kind: &str) -> Res<Vec<(String, String, u128)>> {
        let operand = self.record(kind)?;
        let cls = match operand.get("RegClass") {
            Some(rc) => str_of(get(rc, "def")?)?,
            None => kind,
        };
        if !has_super(self.record(cls)?, "RegisterClass")? {
            return Ok(Vec::new());
        }
        let rules = methods.get(opt_str(operand, "EncoderMethod", "")?);
        let mut result = Vec::new();
        for reg in self.members(cls)? {
            let record = self.record(&reg)?;
            let mut encoding = integer(array_of(get(record, "HWEncoding")?)?)?;
            if let Some(rules) = rules {
                let rule = rules
                    .iter()
                    .find(|r| r.regs.contains(&reg))
                    .ok_or_else(|| format!("assertion failed: ({kind}, {reg})"))?;
                encoding = match rule.shift {
                    Some(s) => {
                        if s >= 128 || (encoding != 0 && encoding.leading_zeros() < s) {
                            return Err("register encoding exceeds 128 bits".into());
                        }
                        (encoding << s) | rule.value
                    }
                    None => rule.value,
                };
            }
            result.push((reg, str_of(get(record, "AsmName")?)?.to_string(), encoding));
        }
        Ok(result)
    }
}

fn parse_methods(g: &mut Gen, emitter: &str) -> Res<HashMap<String, Vec<Rule>>> {
    let method_re = Regex::new(r"(?s)void AIE2PMCCodeEmitter::(\w+)\((.*?)\n\}").unwrap();
    let rule_re = Regex::new(r"(?s)(?:if|else if)\s*\((.*?)\)\s*\{\s*Result = ([^;]+);").unwrap();
    let ws = Regex::new(r"\s+").unwrap();
    let cls_re = Regex::new(r"\AAIE2PMCRegisterClasses\[AIE2P::(\w+)RegClassID\]\.contains\(Reg\)\z").unwrap();
    let reg_re = Regex::new(r"\AReg==AIE2P::(\w+)\z").unwrap();
    let shift_re = Regex::new(r"\A\(Encoding << (\d+)\) \| (0b[01]+)\z").unwrap();
    let const_re = Regex::new(r"\A0b[01]+\z").unwrap();
    let mut methods = HashMap::new();
    for m in method_re.captures_iter(emitter) {
        let (method, body) = (&m[1], &m[2]);
        let mut rules = Vec::new();
        for r in rule_re.captures_iter(body) {
            let condition = ws.replace_all(&r[1], "").into_owned();
            let expression = &r[2];
            let cls = cls_re.captures(&condition);
            let reg = reg_re.captures(&condition);
            if cls.is_none() && reg.is_none() {
                return Err(format!("assertion failed: {condition}"));
            }
            let shift = shift_re.captures(expression);
            if shift.is_none() && !const_re.is_match(expression) {
                return Err(format!("assertion failed: {expression}"));
            }
            let regs = match (&cls, &reg) {
                (Some(c), _) => g.members(&c[1])?,
                (None, Some(r)) => vec![r[1].to_string()],
                _ => unreachable!(),
            };
            let (sh, val) = match &shift {
                Some(s) => (
                    Some(s[1].parse::<u32>().map_err(|e| format!("{}: {e}", &s[1]))?),
                    parse_bin(&s[2])?,
                ),
                None => (None, parse_bin(expression)?),
            };
            rules.push(Rule { regs, shift: sh, value: val });
        }
        if rules.is_empty() {
            return Err(format!("assertion failed: {method}"));
        }
        methods.insert(method.to_string(), rules);
    }
    Ok(methods)
}

fn generate(records: &Value, emitter: &str) -> Res<(String, usize, usize, usize)> {
    let mut g = Gen { records, members_cache: HashMap::new() };
    let methods = parse_methods(&mut g, emitter)?;
    let map = records.as_object().ok_or("records.json is not an object")?;

    let mut instructions: Vec<(&String, &Value)> = Vec::new();
    let mut formats: Vec<(&String, &Value)> = Vec::new();
    for (name, r) in map {
        if !r.is_object() {
            continue;
        }
        let supers = r.get("!superclasses").and_then(Value::as_array);
        let has = |s: &str| supers.is_some_and(|a| a.iter().any(|x| x.as_str() == Some(s)));
        if has("AIE2PSlotInst") && !truthy(get(r, "isPseudo")?) {
            instructions.push((name, r));
        }
        if has("AIE2PCompositeInst") && !truthy(get(r, "isPseudo")?) {
            formats.push((name, r));
        }
    }
    instructions.sort_by(|a, b| a.0.cmp(b.0));
    let mut sized: Vec<(u64, &String, &Value)> = Vec::new();
    for (n, r) in formats {
        sized.push((uint_of(get(r, "Size")?)?, n, r));
    }
    sized.sort_by(|a, b| (a.0, a.1).cmp(&(b.0, b.1)));

    let mut kind_set: Vec<&str> = Vec::new();
    for (_, r) in &instructions {
        for dag in ["OutOperandList", "InOperandList"] {
            for item in array_of(get(get(r, dag)?, "args")?)? {
                kind_set.push(str_of(get(item.get(0).ok_or("dag arg missing")?, "def")?)?);
            }
        }
    }
    kind_set.sort_unstable();
    kind_set.dedup();
    let kinds = kind_set;

    let mut out: Vec<String> = vec![HEADER.to_string()];
    let mut register_tables: HashMap<&str, usize> = HashMap::new();
    for (index, kind) in kinds.iter().enumerate() {
        let regs = g.reg_table(&methods, kind)?;
        register_tables.insert(kind, index);
        out.push(format!("static REGS_{index}: &[RegisterEncoding] = &["));
        for (name, asm, value) in regs {
            out.push(format!("RegisterEncoding {{ name: {}, asm: {}, value: {value} }},", q(&name), q(&asm)));
        }
        out.push("];".to_string());
    }

    out.push("pub static FORMATS: &[Format] = &[".to_string());
    for (_, name, record) in &sized {
        let inst = array_of(get(record, "Inst")?)?;
        let (mask, value, dc, mut fields) = bit_layout(inst)?;
        if inst.len() as u64 != uint_of(get(record, "Size")?)? * 8 {
            return Err(format!("assertion failed: len(Inst) == Size*8 for {name}"));
        }
        let mut order: HashMap<&str, usize> = HashMap::new();
        for (i, item) in array_of(get(get(record, "InOperandList")?, "args")?)?.iter().enumerate() {
            order.insert(str_of(item.get(1).ok_or("dag arg missing name")?)?, i);
        }
        let mut keyed = Vec::new();
        for f in fields.drain(..) {
            let key = *order.get(f.name.as_str()).ok_or_else(|| format!("KeyError: {:?}", f.name))?;
            keyed.push((key, f));
        }
        keyed.sort_by_key(|(k, _)| *k);
        let mut slot_fields = Vec::new();
        for (_, f) in &keyed {
            if f.source != 0 || f.width != array_of(get(record, &f.name)?)?.len() {
                return Err(format!("assertion failed: ({name}, {})", f.name));
            }
            slot_fields.push(format!(
                "SlotField {{ slot: Slot::{}, lsb: {}, width: {} }}",
                slot_name(&f.name)?,
                f.lsb,
                f.width
            ));
        }
        out.push(format!(
            "Format {{ name: {}, bits: {}, mask: {mask:#x}, value: {value:#x}, dontcare_mask: {dc:#x}, slots: &[{}] }},",
            q(name),
            inst.len(),
            slot_fields.join(",")
        ));
    }

    out.push("];\npub static ENCODINGS: &[Encoding] = &[".to_string());
    for (name, record) in &instructions {
        let (mask, value, dc, fields) = bit_layout(array_of(get(record, "Inst")?)?)?;
        let fields_rs = fields
            .iter()
            .map(|f| format!("BitField {{ name: {}, lsb: {}, width: {}, source_lsb: {} }}", q(&f.name), f.lsb, f.width, f.source))
            .collect::<Vec<_>>()
            .join(",");
        let mut operands = Vec::new();
        for dag in ["OutOperandList", "InOperandList"] {
            for item in array_of(get(get(record, dag)?, "args")?)? {
                let kind = str_of(get(item.get(0).ok_or("dag arg missing")?, "def")?)?;
                let n = str_of(item.get(1).ok_or("dag arg missing name")?)?;
                let op = g.record(kind)?;
                let width = fields
                    .iter()
                    .filter(|f| f.name == n)
                    .map(|f| f.source as usize + f.width)
                    .max()
                    .unwrap_or(0);
                operands.push(format!(
                    "Operand {{ name: {}, kind: {}, width: {width}, output: {}, encoder: {}, decoder: {}, printer: {}, registers: REGS_{} }}",
                    q(n),
                    q(kind),
                    dag == "OutOperandList",
                    q(opt_str(op, "EncoderMethod", "")?),
                    q(opt_str(op, "DecoderMethod", "")?),
                    q(opt_str(op, "PrintMethod", "printOperand")?),
                    register_tables[kind]
                ));
            }
        }
        let asm = str_of(get(record, "AsmString")?)?;
        let mnemonic = asm.split_whitespace().next().ok_or("IndexError: list index out of range")?;
        let slot_def = str_of(get(get(record, "Slot")?, "def")?)?;
        let slot = slot_name(slot_def.strip_suffix("_slot").unwrap_or(slot_def))?;
        out.push(format!(
            "Encoding {{ name: {}, mnemonic: {}, asm: {}, slot: Slot::{slot}, mask: {mask:#x}, value: {value:#x}, dontcare_mask: {dc:#x}, fields: &[{fields_rs}], operands: &[{}], itinerary: {}, constraints: {} }},",
            q(name),
            q(mnemonic),
            q(asm),
            operands.join(","),
            q(str_of(get(get(record, "Itinerary")?, "def")?)?),
            q(str_of(get(record, "Constraints")?)?)
        ));
    }
    out.push("];\n".to_string());
    Ok((out.join("\n"), instructions.len(), sized.len(), kinds.len()))
}

struct Options {
    llvm: PathBuf,
    output: PathBuf,
    tblgen: String,
    upstream: PathBuf,
}

const USAGE: &str = "usage: tblgen2rs [-h] --llvm LLVM --output OUTPUT [--tblgen TBLGEN]\n                 [--upstream-include UPSTREAM_INCLUDE]";

fn parse_args(args: &[String]) -> Res<Option<Options>> {
    const LONG: [&str; 5] = ["--help", "--llvm", "--output", "--tblgen", "--upstream-include"];
    let (mut llvm, mut output, mut tblgen, mut upstream) = (None, None, None, None);
    let mut i = 0;
    let fail = |msg: String| format!("{USAGE}\ntblgen2rs: error: {msg}");
    while i < args.len() {
        let arg = &args[i];
        i += 1;
        if arg == "-h" {
            println!("{USAGE}\n\n{DESCRIPTION}");
            return Ok(None);
        }
        if !arg.starts_with("--") {
            return Err(fail(format!("unrecognized arguments: {arg}")));
        }
        let (flag, inline) = match arg.split_once('=') {
            Some((f, v)) => (f, Some(v.to_string())),
            None => (arg.as_str(), None),
        };
        let matches: Vec<&str> = if LONG.contains(&flag) {
            vec![LONG.iter().copied().find(|l| *l == flag).unwrap()]
        } else {
            LONG.iter().copied().filter(|l| l.starts_with(flag)).collect()
        };
        let name = match matches.as_slice() {
            [one] => *one,
            [] => return Err(fail(format!("unrecognized arguments: {arg}"))),
            many => return Err(fail(format!("ambiguous option: {flag} could match {}", many.join(", ")))),
        };
        if name == "--help" {
            println!("{USAGE}\n\n{DESCRIPTION}");
            return Ok(None);
        }
        let value = match inline {
            Some(v) => v,
            None => {
                let v = args.get(i).filter(|v| !v.starts_with('-') || v.as_str() == "-");
                match v {
                    Some(v) => {
                        i += 1;
                        v.clone()
                    }
                    None => return Err(fail(format!("argument {name}: expected one argument"))),
                }
            }
        };
        match name {
            "--llvm" => llvm = Some(value),
            "--output" => output = Some(value),
            "--tblgen" => tblgen = Some(value),
            _ => upstream = Some(value),
        }
    }
    let (Some(llvm), Some(output)) = (llvm.clone(), output.clone()) else {
        let mut missing = Vec::new();
        if llvm.is_none() {
            missing.push("--llvm");
        }
        if output.is_none() {
            missing.push("--output");
        }
        return Err(fail(format!("the following arguments are required: {}", missing.join(", "))));
    };
    Ok(Some(Options {
        llvm: PathBuf::from(llvm),
        output: PathBuf::from(output),
        tblgen: tblgen.unwrap_or_else(|| "llvm-tblgen-18".to_string()),
        upstream: PathBuf::from(upstream.unwrap_or_else(|| "/usr/lib/llvm-18/include".to_string())),
    }))
}

pub fn run(args: &[String]) -> Result<(), String> {
    let Some(opts) = parse_args(args)? else {
        return Ok(());
    };
    let resolved = fs::canonicalize(&opts.llvm).unwrap_or_else(|_| {
        if opts.llvm.is_absolute() {
            opts.llvm.clone()
        } else {
            std::env::current_dir().map(|d| d.join(&opts.llvm)).unwrap_or_else(|_| opts.llvm.clone())
        }
    });
    let records = dump_records(&resolved, &opts.tblgen, &opts.upstream)?;
    let emitter = read_text(&opts.llvm.join("llvm/lib/Target/AIE/MCTargetDesc/aie2p/AIE2PMCCodeEmitterGen.inc"))?;
    let (text, insts, formats, operands) = generate(&records, &emitter)?;
    if let Some(parent) = opts.output.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("{}: {e}", parent.display()))?;
    }
    write_text(&opts.output, &text)?;
    println!(
        "Generated {insts} instructions, {formats} formats, {operands} operand kinds -> {}",
        opts.output.display()
    );
    Ok(())
}
