[package]
name = "peacemaker-lift"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
peacemaker-ir = { path = "../peacemaker-ir" }
object = { version = "0.38", features = ["write"] }
rmp-serde = "1"
rmpv = "1"
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
insta = "1"
