; PM-native gfx1151 gate/up SiLU epilogue v2 (coop27): ief_silu with the incumbent's SiLU group DAG register-renamed to a
; low VGPR footprint (gate v8..v15, up v16..v23, scratch v24..v71; SGPRs/vcc unchanged) for occupancy. Same instruction
; sequence, operands and mode bits as `ief_silu`, so the same bits. Generated by native/build.sh as
; ief_silu2.head.s + silu_dag_lowreg.inc (awk renaming of silu_dag_gfx1151.inc) + ief_silu2.tail.s. Kernarg / grid as ief_silu.
.amdgcn_target "amdgcn-amd-amdhsa--gfx1151"
.amdhsa_code_object_version 6
.text
.protected ief_silu2
.globl ief_silu2
.p2align 8
.type ief_silu2,@function
ief_silu2:
    s_load_b256 s[16:23], s[0:1], null
    s_load_b32 s24, s[0:1], 0x20
    s_lshr_b32 s5, s2, 1
    s_and_b32 s6, s2, 1
    s_lshr_b32 s7, s3, 1
    s_and_b32 s8, s3, 1
    s_waitcnt lgkmcnt(0)
    s_mul_i32 s9, s7, s23
    s_add_u32 s9, s9, s5
    s_lshl_b32 s10, s4, 2
    s_lshl_b32 s11, s8, 1
    s_add_u32 s10, s10, s11
    s_mul_i32 s10, s10, s22
    s_lshl_b32 s11, s9, 1
    s_add_u32 s11, s11, s6
    s_add_u32 s10, s10, s11
    s_lshl_b32 s10, s10, 13
    s_add_u32 s12, s16, s10
    s_addc_u32 s13, s17, 0
    s_and_b32 s11, s4, 1
    s_lshl_b32 s14, s8, 1
    s_add_u32 s14, s14, s11
    s_lshl_b32 s14, s14, 6
    s_lshl_b32 s15, s7, 8
    s_add_u32 s14, s14, s15
    s_lshl_b32 s15, s5, 8
    s_lshr_b32 s11, s4, 1
    s_lshl_b32 s11, s11, 6
    s_add_u32 s15, s15, s11
    s_lshl_b32 s11, s6, 5
    s_add_u32 s15, s15, s11
    s_add_u32 s15, s15, s21
    s_lshl_b32 s25, s24, 14
    s_add_u32 s26, s12, s25
    s_addc_u32 s27, s13, 0
    v_and_b32_e32 v1, 7, v0
    v_bfe_u32 v2, v0, 3, 2
    v_lshrrev_b32_e32 v3, 5, v0
    v_lshl_add_u32 v4, v3, 3, v1
    v_add_nc_u32_e32 v4, s14, v4
    v_mul_lo_u32 v5, v4, s20
    v_lshl_add_u32 v6, v2, 3, s15
    v_add_nc_u32_e32 v5, v5, v6
    v_lshlrev_b32_e32 v5, 2, v5
    v_lshlrev_b32_e32 v7, 5, v0
    global_load_b128 v[8:11], v7, s[12:13] glc dlc
    global_load_b128 v[12:15], v7, s[12:13] offset:16 glc dlc
    global_load_b128 v[16:19], v7, s[26:27] glc dlc
    global_load_b128 v[20:23], v7, s[26:27] offset:16 glc dlc
    s_waitcnt vmcnt(0)
v_mul_f32_e32 v24, 0xbfb8aa3b, v8
v_mul_f32_e32 v30, 0xbfb8aa3b, v9
v_mul_f32_e32 v36, 0xbfb8aa3b, v10
v_mul_f32_e32 v42, 0xbfb8aa3b, v11
v_mul_f32_e32 v48, 0xbfb8aa3b, v12
v_mul_f32_e32 v54, 0xbfb8aa3b, v13
v_mul_f32_e32 v60, 0xbfb8aa3b, v14
v_mul_f32_e32 v66, 0xbfb8aa3b, v15
v_fma_f32 v25, 0xbfb8aa3b, v8, -v24
v_fma_f32 v31, 0xbfb8aa3b, v9, -v30
v_fma_f32 v37, 0xbfb8aa3b, v10, -v36
v_fma_f32 v43, 0xbfb8aa3b, v11, -v42
v_fma_f32 v49, 0xbfb8aa3b, v12, -v48
v_fma_f32 v55, 0xbfb8aa3b, v13, -v54
v_fma_f32 v61, 0xbfb8aa3b, v14, -v60
v_fma_f32 v67, 0xbfb8aa3b, v15, -v66
v_fmac_f32_e32 v25, 0xb2a5705f, v8
v_fmac_f32_e32 v31, 0xb2a5705f, v9
v_fmac_f32_e32 v37, 0xb2a5705f, v10
v_fmac_f32_e32 v43, 0xb2a5705f, v11
v_fmac_f32_e32 v49, 0xb2a5705f, v12
v_fmac_f32_e32 v55, 0xb2a5705f, v13
v_fmac_f32_e32 v61, 0xb2a5705f, v14
v_fmac_f32_e32 v67, 0xb2a5705f, v15
v_rndne_f32_e32 v26, v24
v_rndne_f32_e32 v32, v30
v_rndne_f32_e32 v38, v36
v_rndne_f32_e32 v44, v42
v_rndne_f32_e32 v50, v48
v_rndne_f32_e32 v56, v54
v_rndne_f32_e32 v62, v60
v_rndne_f32_e32 v68, v66
v_sub_f32_e32 v24, v24, v26
v_sub_f32_e32 v30, v30, v32
v_sub_f32_e32 v36, v36, v38
v_sub_f32_e32 v42, v42, v44
v_sub_f32_e32 v48, v48, v50
v_sub_f32_e32 v54, v54, v56
v_sub_f32_e32 v60, v60, v62
v_sub_f32_e32 v66, v66, v68
v_add_f32_e32 v24, v24, v25
v_add_f32_e32 v30, v30, v31
v_add_f32_e32 v36, v36, v37
v_add_f32_e32 v42, v42, v43
v_add_f32_e32 v48, v48, v49
v_add_f32_e32 v54, v54, v55
v_add_f32_e32 v60, v60, v61
v_add_f32_e32 v66, v66, v67
v_exp_f32_e32 v24, v24
v_exp_f32_e32 v30, v30
v_exp_f32_e32 v36, v36
v_exp_f32_e32 v42, v42
v_exp_f32_e32 v48, v48
v_exp_f32_e32 v54, v54
v_exp_f32_e32 v60, v60
v_exp_f32_e32 v66, v66
v_cvt_i32_f32_e32 v26, v26
v_cvt_i32_f32_e32 v32, v32
v_cvt_i32_f32_e32 v38, v38
v_cvt_i32_f32_e32 v44, v44
v_cvt_i32_f32_e32 v50, v50
v_cvt_i32_f32_e32 v56, v56
v_cvt_i32_f32_e32 v62, v62
v_cvt_i32_f32_e32 v68, v68
v_ldexp_f32 v24, v24, v26
v_ldexp_f32 v30, v30, v32
v_ldexp_f32 v36, v36, v38
v_ldexp_f32 v42, v42, v44
v_ldexp_f32 v48, v48, v50
v_ldexp_f32 v54, v54, v56
v_ldexp_f32 v60, v60, v62
v_ldexp_f32 v66, v66, v68
v_cmp_nlt_f32_e64 s48, 0x42ce8ed0, v8
v_cmp_nlt_f32_e64 s50, 0x42ce8ed0, v9
v_cmp_nlt_f32_e64 s52, 0x42ce8ed0, v10
v_cmp_nlt_f32_e64 s54, 0x42ce8ed0, v11
v_cmp_nlt_f32_e64 s56, 0x42ce8ed0, v12
v_cmp_nlt_f32_e64 s58, 0x42ce8ed0, v13
v_cmp_nlt_f32_e64 s60, 0x42ce8ed0, v14
v_cmp_nlt_f32_e64 s62, 0x42ce8ed0, v15
v_cndmask_b32_e64 v24, 0, v24, s48
v_cndmask_b32_e64 v30, 0, v30, s50
v_cndmask_b32_e64 v36, 0, v36, s52
v_cndmask_b32_e64 v42, 0, v42, s54
v_cndmask_b32_e64 v48, 0, v48, s56
v_cndmask_b32_e64 v54, 0, v54, s58
v_cndmask_b32_e64 v60, 0, v60, s60
v_cndmask_b32_e64 v66, 0, v66, s62
v_cmp_ngt_f32_e64 s64, 0xc2b17218, v8
v_cmp_ngt_f32_e64 s66, 0xc2b17218, v9
v_cmp_ngt_f32_e64 s68, 0xc2b17218, v10
v_cmp_ngt_f32_e64 s70, 0xc2b17218, v11
v_cmp_ngt_f32_e64 s72, 0xc2b17218, v12
v_cmp_ngt_f32_e64 s74, 0xc2b17218, v13
v_cmp_ngt_f32_e64 s76, 0xc2b17218, v14
v_cmp_ngt_f32_e64 s78, 0xc2b17218, v15
v_cndmask_b32_e64 v24, 0x7f800000, v24, s64
v_cndmask_b32_e64 v30, 0x7f800000, v30, s66
v_cndmask_b32_e64 v36, 0x7f800000, v36, s68
v_cndmask_b32_e64 v42, 0x7f800000, v42, s70
v_cndmask_b32_e64 v48, 0x7f800000, v48, s72
v_cndmask_b32_e64 v54, 0x7f800000, v54, s74
v_cndmask_b32_e64 v60, 0x7f800000, v60, s76
v_cndmask_b32_e64 v66, 0x7f800000, v66, s78
v_add_f32_e32 v24, 1.0, v24
v_add_f32_e32 v30, 1.0, v30
v_add_f32_e32 v36, 1.0, v36
v_add_f32_e32 v42, 1.0, v42
v_add_f32_e32 v48, 1.0, v48
v_add_f32_e32 v54, 1.0, v54
v_add_f32_e32 v60, 1.0, v60
v_add_f32_e32 v66, 1.0, v66
v_div_scale_f32 v25, null, v24, v24, v8
v_div_scale_f32 v31, null, v30, v30, v9
v_div_scale_f32 v37, null, v36, v36, v10
v_div_scale_f32 v43, null, v42, v42, v11
v_div_scale_f32 v49, null, v48, v48, v12
v_div_scale_f32 v55, null, v54, v54, v13
v_div_scale_f32 v61, null, v60, v60, v14
v_div_scale_f32 v67, null, v66, v66, v15
v_div_scale_f32 v26, s80, v8, v24, v8
v_div_scale_f32 v32, s82, v9, v30, v9
v_div_scale_f32 v38, s84, v10, v36, v10
v_div_scale_f32 v44, s86, v11, v42, v11
v_div_scale_f32 v50, s88, v12, v48, v12
v_div_scale_f32 v56, s90, v13, v54, v13
v_div_scale_f32 v62, s92, v14, v60, v14
v_div_scale_f32 v68, s94, v15, v66, v15
v_rcp_f32_e32 v27, v25
v_rcp_f32_e32 v33, v31
v_rcp_f32_e32 v39, v37
v_rcp_f32_e32 v45, v43
v_rcp_f32_e32 v51, v49
v_rcp_f32_e32 v57, v55
v_rcp_f32_e32 v63, v61
v_rcp_f32_e32 v69, v67
v_fma_f32 v28, -v25, v27, 1.0
v_fma_f32 v34, -v31, v33, 1.0
v_fma_f32 v40, -v37, v39, 1.0
v_fma_f32 v46, -v43, v45, 1.0
v_fma_f32 v52, -v49, v51, 1.0
v_fma_f32 v58, -v55, v57, 1.0
v_fma_f32 v64, -v61, v63, 1.0
v_fma_f32 v70, -v67, v69, 1.0
v_fmac_f32_e32 v27, v28, v27
v_fmac_f32_e32 v33, v34, v33
v_fmac_f32_e32 v39, v40, v39
v_fmac_f32_e32 v45, v46, v45
v_fmac_f32_e32 v51, v52, v51
v_fmac_f32_e32 v57, v58, v57
v_fmac_f32_e32 v63, v64, v63
v_fmac_f32_e32 v69, v70, v69
v_mul_f32_e32 v28, v26, v27
v_mul_f32_e32 v34, v32, v33
v_mul_f32_e32 v40, v38, v39
v_mul_f32_e32 v46, v44, v45
v_mul_f32_e32 v52, v50, v51
v_mul_f32_e32 v58, v56, v57
v_mul_f32_e32 v64, v62, v63
v_mul_f32_e32 v70, v68, v69
v_fma_f32 v29, -v25, v28, v26
v_fma_f32 v35, -v31, v34, v32
v_fma_f32 v41, -v37, v40, v38
v_fma_f32 v47, -v43, v46, v44
v_fma_f32 v53, -v49, v52, v50
v_fma_f32 v59, -v55, v58, v56
v_fma_f32 v65, -v61, v64, v62
v_fma_f32 v71, -v67, v70, v68
v_fmac_f32_e32 v28, v29, v27
v_fmac_f32_e32 v34, v35, v33
v_fmac_f32_e32 v40, v41, v39
v_fmac_f32_e32 v46, v47, v45
v_fmac_f32_e32 v52, v53, v51
v_fmac_f32_e32 v58, v59, v57
v_fmac_f32_e32 v64, v65, v63
v_fmac_f32_e32 v70, v71, v69
v_fma_f32 v29, -v25, v28, v26
v_fma_f32 v35, -v31, v34, v32
v_fma_f32 v41, -v37, v40, v38
v_fma_f32 v47, -v43, v46, v44
v_fma_f32 v53, -v49, v52, v50
v_fma_f32 v59, -v55, v58, v56
v_fma_f32 v65, -v61, v64, v62
v_fma_f32 v71, -v67, v70, v68
s_mov_b32 vcc_lo, s80
v_div_fmas_f32 v29, v29, v27, v28
s_mov_b32 vcc_lo, s82
v_div_fmas_f32 v35, v35, v33, v34
s_mov_b32 vcc_lo, s84
v_div_fmas_f32 v41, v41, v39, v40
s_mov_b32 vcc_lo, s86
v_div_fmas_f32 v47, v47, v45, v46
s_mov_b32 vcc_lo, s88
v_div_fmas_f32 v53, v53, v51, v52
s_mov_b32 vcc_lo, s90
v_div_fmas_f32 v59, v59, v57, v58
s_mov_b32 vcc_lo, s92
v_div_fmas_f32 v65, v65, v63, v64
s_mov_b32 vcc_lo, s94
v_div_fmas_f32 v71, v71, v69, v70
v_div_fixup_f32 v29, v29, v24, v8
v_div_fixup_f32 v35, v35, v30, v9
v_div_fixup_f32 v41, v41, v36, v10
v_div_fixup_f32 v47, v47, v42, v11
v_div_fixup_f32 v53, v53, v48, v12
v_div_fixup_f32 v59, v59, v54, v13
v_div_fixup_f32 v65, v65, v60, v14
v_div_fixup_f32 v71, v71, v66, v15
v_mul_f32_e32 v8, v29, v16
v_mul_f32_e32 v9, v35, v17
v_mul_f32_e32 v10, v41, v18
v_mul_f32_e32 v11, v47, v19
v_mul_f32_e32 v12, v53, v20
v_mul_f32_e32 v13, v59, v21
v_mul_f32_e32 v14, v65, v22
v_mul_f32_e32 v15, v71, v23
    global_store_b128 v5, v[8:11], s[18:19]
    global_store_b128 v5, v[12:15], s[18:19] offset:16
    s_endpgm
.Lief_silu2_end:
.size ief_silu2, .Lief_silu2_end-ief_silu2
.section .rodata,"a",@progbits
.p2align 6
.amdhsa_kernel ief_silu2
    .amdhsa_group_segment_fixed_size 0
    .amdhsa_private_segment_fixed_size 0
    .amdhsa_kernarg_size 40
    .amdhsa_user_sgpr_count 2
    .amdhsa_user_sgpr_dispatch_ptr 0
    .amdhsa_user_sgpr_queue_ptr 0
    .amdhsa_user_sgpr_kernarg_segment_ptr 1
    .amdhsa_user_sgpr_dispatch_id 0
    .amdhsa_user_sgpr_private_segment_size 0
    .amdhsa_wavefront_size32 1
    .amdhsa_uses_dynamic_stack 0
    .amdhsa_enable_private_segment 0
    .amdhsa_system_sgpr_workgroup_id_x 1
    .amdhsa_system_sgpr_workgroup_id_y 1
    .amdhsa_system_sgpr_workgroup_id_z 1
    .amdhsa_system_sgpr_workgroup_info 0
    .amdhsa_system_vgpr_workitem_id 0
    .amdhsa_next_free_vgpr 72
    .amdhsa_next_free_sgpr 96
    .amdhsa_reserve_vcc 1
    .amdhsa_float_round_mode_32 0
    .amdhsa_float_round_mode_16_64 0
    .amdhsa_float_denorm_mode_32 3
    .amdhsa_float_denorm_mode_16_64 3
    .amdhsa_fp16_overflow 0
    .amdhsa_workgroup_processor_mode 1
    .amdhsa_memory_ordered 1
    .amdhsa_forward_progress 1
    .amdhsa_dx10_clamp 1
    .amdhsa_ieee_mode 1
    .amdhsa_shared_vgpr_count 0
    .amdhsa_exception_fp_ieee_invalid_op 0
    .amdhsa_exception_fp_denorm_src 0
    .amdhsa_exception_fp_ieee_div_zero 0
    .amdhsa_exception_fp_ieee_overflow 0
    .amdhsa_exception_fp_ieee_underflow 0
    .amdhsa_exception_fp_ieee_inexact 0
    .amdhsa_exception_int_div_zero 0
    .amdhsa_inst_pref_size ((instprefsize(.Lief_silu2_end-ief_silu2)<<4)&1008)>>4
.end_amdhsa_kernel
.text
.amdgpu_metadata
---
amdhsa.kernels:
  - .args:
      - .address_space: global
        .name: c
        .offset: 0
        .size: 8
        .value_kind: global_buffer
      - .address_space: global
        .name: y
        .offset: 8
        .size: 8
        .value_kind: global_buffer
      - .name: ldy
        .offset: 16
        .size: 4
        .value_kind: by_value
      - .name: col0
        .offset: 20
        .size: 4
        .value_kind: by_value
      - .name: waves
        .offset: 24
        .size: 4
        .value_kind: by_value
      - .name: nw
        .offset: 28
        .size: 4
        .value_kind: by_value
      - .name: half
        .offset: 32
        .size: 4
        .value_kind: by_value
    .group_segment_fixed_size: 0
    .kernarg_segment_align: 8
    .kernarg_segment_size: 40
    .max_flat_workgroup_size: 256
    .name: ief_silu2
    .private_segment_fixed_size: 0
    .sgpr_count: 98
    .sgpr_spill_count: 0
    .symbol: ief_silu2.kd
    .uniform_work_group_size: 1
    .uses_dynamic_stack: false
    .vgpr_count: 72
    .vgpr_spill_count: 0
    .wavefront_size: 32
    .workgroup_processor_mode: 1
amdhsa.target: amdgcn-amd-amdhsa--gfx1151
amdhsa.version: [1, 2]
...
.end_amdgpu_metadata
