#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Exhaustive equivalence of the lean GDN SiLU against the imported hipcc golden.

    silu_exhaust.py <workdir>      (one visible gfx1201 device, e.g. ROCR_VISIBLE_DEVICES=<uuid>)

Both committed regions (`kernels/fp8_gemm.gdn.conv_silu.region.s` and
`..._lean.region.s`) must start with the same four conv MAC lines. Their
remaining SiLU lines are turned verbatim into inline asm (registers renamed to
asm operands; the conv result is the only VGPR input) and run for all 2^32 f32
bit patterns of the conv result on the GPU. Every output bit must agree
(NaN payloads and signed zeros included). The test kernel's descriptor must use
the F2 float mode (round-nearest, f32/f64 denormals kept, no fp16 overflow
clamp); a `s_wait_alu depctr_va_vcc(0)` precedes every VCC read. Exit status 0
only on zero mismatches.
"""
import os, pathlib, re, subprocess, sys

HERE = pathlib.Path(__file__).resolve().parent
KERNELS = HERE.parent.parent / "kernels"
CLAMP = "0x43000000"  # the builder's clamp SGPR value (128.0)


def instructions(path):
    out, header = [], {}
    for line in path.read_text().splitlines():
        t = line.strip()
        if t.startswith(";"):
            m = re.match(r";\s*(inputs|sinputs|outputs):\s*(.*)", t)
            if m: header[m[1]] = dict(p.split("=") for p in m[2].split())
            continue
        if t: out.append(t)
    return out, header


def asm(lines, x, out, sgprs):
    """Inline-asm body for the SiLU lines: x is the input VGPR, out the result VGPR."""
    vregs = []
    for l in lines:
        for r in re.findall(r"(?<![\w-])-?v(\d+)\b", l):
            r = f"v{r}"
            if r != x and r != out and r not in vregs: vregs.append(r)
    outs = [out] + vregs
    names = {r: f"%{i}" for i, r in enumerate(outs)}
    names[x] = f"%{len(outs)}"
    for k, s in enumerate(sgprs): names[s] = f"%{len(outs) + 1 + k}"
    body = []
    for l in lines:
        if "vcc_lo" in l.split(",", 1)[-1] and not l.startswith("v_cmp") and not l.startswith("v_div_scale"):
            if not (body and body[-1] == "s_wait_alu depctr_va_vcc(0)"): body.append("s_wait_alu depctr_va_vcc(0)")
        body.append(re.sub(r"\b([vs]\d+)\b", lambda m: names.get(m[1], m[1]), l))
    text = "\n".join(f'        "{b}\\n"' for b in body)
    decl = ", ".join(f"t{i}" for i in range(len(vregs)))
    outc = ", ".join(['"=&v"(o)'] + [f'"=&v"(t{i})' for i in range(len(vregs))])
    inc = ", ".join(['"v"(x)'] + [f'"s"(__uint_as_float({CLAMP}u))' for _ in sgprs])
    return f"    float o{', ' + decl if decl else ''};\n    asm volatile(\n{text}\n        : {outc} : {inc} : \"vcc_lo\");\n    return o;"


def main():
    work = pathlib.Path(sys.argv[1]); work.mkdir(parents=True, exist_ok=True)
    gold, gh = instructions(KERNELS / "fp8_gemm.gdn.conv_silu.region.s")
    # LEAN_REGION overrides the candidate (negative controls only).
    lean, lh = instructions(pathlib.Path(os.environ.get("LEAN_REGION", KERNELS / "fp8_gemm.gdn.conv_silu_lean.region.s")))
    assert gold[:4] == lean[:4], "conv MAC lines differ"
    assert gh["inputs"] == lh["inputs"] and gh["outputs"] == lh["outputs"], "interfaces differ"
    x = gold[0].split()[1].rstrip(",")
    assert all(l.split()[1].rstrip(",") == x for l in gold[:4]), "conv accumulator"
    for lines in (gold[4:], lean[4:]):
        assert all(l.startswith("s_") or l.split()[1].rstrip(",") != x for l in lines), "SiLU redefines x"
    ref = asm(gold[4:], x, gh["outputs"]["out"], [])
    new = asm(lean[4:], x, lh["outputs"]["out"], sorted(lh.get("sinputs", {}).values()))
    src = f"""// Generated by silu_exhaust.py from the committed regions. Do not edit.
#include <hip/hip_runtime.h>
#include <cstdio>
#include <cstring>
__device__ __forceinline__ float ref(float x) {{
{ref}
}}
__device__ __forceinline__ float lean(float x) {{
{new}
}}
__global__ void run(unsigned long long base, unsigned long long* bad, unsigned* first) {{
    const unsigned bits = (unsigned)(base + (unsigned long long)blockIdx.x * blockDim.x + threadIdx.x);
    const float x = __uint_as_float(bits);
    const unsigned a = __float_as_uint(ref(x)), b = __float_as_uint(lean(x));
    if (a != b) {{ unsigned long long k = atomicAdd(bad, 1ull); if (k < 16) {{ first[3 * k] = bits; first[3 * k + 1] = a; first[3 * k + 2] = b; }} }}
}}
int main() {{
    int n = 0; hipGetDeviceCount(&n);
    hipDeviceProp_t p; hipGetDeviceProperties(&p, 0);
    char bus[64]; hipDeviceGetPCIBusId(bus, sizeof bus, 0);
    printf("DEVICE count=%d arch=%s bus=%s\\n", n, p.gcnArchName, bus);
    if (n != 1 || strncmp(p.gcnArchName, "gfx1201", 7) != 0) return 2;
    unsigned long long* bad; unsigned* first;
    hipMalloc(&bad, 8); hipMalloc(&first, 16 * 12); hipMemset(bad, 0, 8);
    for (unsigned long long b = 0; b < (1ull << 32); b += 1ull << 28) run<<<(1u << 28) / 256, 256>>>(b, bad, first);
    if (hipDeviceSynchronize() != hipSuccess) return 3;
    unsigned long long h = 0; unsigned f[48] = {{}};
    hipMemcpy(&h, bad, 8, hipMemcpyDeviceToHost); hipMemcpy(f, first, sizeof f, hipMemcpyDeviceToHost);
    printf("INPUTS 4294967296 MISMATCHES %llu\\n", h);
    for (unsigned k = 0; k < (h < 16 ? h : 16); ++k) printf("  x=%08x golden=%08x lean=%08x\\n", f[3 * k], f[3 * k + 1], f[3 * k + 2]);
    return h == 0 ? 0 : 1;
}}
"""
    (work / "silu_exhaust.hip").write_text(src)
    subprocess.run(["hipcc", "-O3", "--offload-arch=gfx1201", "-ffp-contract=off", "-Wno-unused-value", "-save-temps", "-o", str(work / "silu_exhaust"), "silu_exhaust.hip"],
                   cwd=work, check=True)
    dev = next(work.glob("silu_exhaust-hip-amdgcn-amd-amdhsa-gfx1201.s")).read_text()
    for key, want in [(".amdhsa_float_round_mode_32", "0"), (".amdhsa_float_round_mode_16_64", "0"),
                      (".amdhsa_float_denorm_mode_32", "3"), (".amdhsa_float_denorm_mode_16_64", "3"), (".amdhsa_fp16_overflow", "0")]:
        got = re.search(rf"{re.escape(key)}\s+(\S+)", dev)
        assert got and got[1] == want, f"test kernel {key} = {got and got[1]}, F2 uses {want}"
    r = subprocess.run([str(work / "silu_exhaust")], capture_output=True, text=True)
    print(r.stdout, end="")
    sys.exit(r.returncode)


if __name__ == "__main__":
    main()
